src/Entity/Wish.php
<?php

namespace App\Entity;

use App\Repository\WishRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=WishRepository::class)
 */
class Wish
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $Title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Author;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isPublished;

    /**
     * @ORM\Column(type="date")
     */
    private $dateCreated;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->Author;
    }

    public function setAuthor(string $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->dateCreated;
    }

    public function setDateCreated(\DateTimeInterface $dateCreated): self
    {
        $this->dateCreated = $dateCreated;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
	/**
	 * @Route("/",name="main_home")
	 */
	function home(){
		return $this->render('main/home.html.twig');
	}

	/**
	 * @Route("/AboutUs",name="main_AboutUs")
	 */
	function AboutUs(){
		return $this->render('main/AboutUs.html.twig');
	}
}

src/Controller/WishController.php
<?php

namespace App\Controller;

use App\Entity\Wish;
use App\Repository\WishRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/wish', name: 'Wish_')]
class WishController extends AbstractController
{
	#[Route('', name: 'List')]
	public function List(EntityManagerInterface $entityManager, WishRepository $wishRepository): Response
	{/*
		$wish = new Wish();
		$wish->setTitle("Faire 2 fois le tour du monde");
		$wish->setAuthor("Moi");
		$wish->setDateCreated(new \DateTime());
		$wish->setDescription("Un petit test de description pour un nouveau wish");
		$wish->setIsPublished(true);
		$entityManager->persist($wish);
		$entityManager->flush();

	    $wish = new Wish();
	    $wish->setTitle("Arrêter la connerie");
	    $wish->setAuthor("Mélaine");
	    $wish->setDateCreated(new \DateTime());
	    $wish->setDescription("Un jour peut-être on y arrivera");
	    $wish->setIsPublished(true);
	    $entityManager->persist($wish);
	    $entityManager->flush();

	    $wish = new Wish();
	    $wish->setTitle("Plus obliger de travailler ");
	    $wish->setAuthor("Moi");
	    $wish->setDateCreated(new \DateTime());
	    $wish->setDescription("");
	    $wish->setIsPublished(false);
	    $entityManager->persist($wish);
	    $entityManager->flush();*/

		$wishes = $wishRepository->findBy([], ['dateCreated' => 'DESC']);

		return $this->render('wish/List.html.twig', ['wishes' => $wishes]);
	}

	#[Route('/details/{id}', name: 'Details')]
	public function Details($id, WishRepository $wishRepository): Response
	{
		$wish = $wishRepository->find($id);

		return $this->render('wish/details.html.twig',['wish'=>$wish]);
	}
}

templates/base.html.twig
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ asset('css/normalize.css') }}">
    <link rel="stylesheet" href="{{ asset('css/base.css') }}">
    <link rel="icon" href="{{ asset('img/icones/favicon.png') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Explora&display=swap" rel="stylesheet">
    <title>  {% block title %} Page de défaut {% endblock %}</title>
</head>
<body>
<header>
    {% block header %}


        {% block nav %}
            {% include 'include/nav.htmlTwig' %}
        {% endblock %}
    {% endblock %}
</header>
<main>
    {% block body %}{% endblock %}
</main>
<footer>
    {% block footer %}{% include 'include/footer.html.twig' %}{% endblock %}
</footer>
</body>
</html>

templates/include/footer.html.twig
&copy; {{ "now"|date('Y') }}

templates/main/AboutUs.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. A accusamus aperiam autem beatae cumque ducimus error
        hic laboriosam maiores molestias mollitia quis reiciendis repellendus vero, voluptas. A earum quia quos.</p>
{% endblock %}

templates/main/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<h1>Bienvenue sur notre site de Listes de souhait à faire !!</h1>
{% endblock %}

templates/wish/List.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des souhaits à faire{% endblock %}

{% block body %}
    <h1>Liste de mes souhaits à faire :</h1>
    {% for wish in wishes %}
        {% if(wish.isPublished) %}
            <a href="{{ path('Wish_Details',{'id': wish.id}) }}" title="{{ wish.title }}"> titre : {{ wish.title }} /
                date : {{ wish.dateCreated |date("d/m/Y") }}</a><br>
        {% endif %}
    {% endfor %}
{% endblock %}

templates/wish/details.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% if(wish.isPublished) %}
        Titre : {{ wish.title }}<br>
        Auteur : {{ wish.author }}<br>
        Date de création du souhait : {{ wish.dateCreated |date("d/m/Y") }}<br>
        Description : {{ wish.description }}<br>
    {% endif %}

{% endblock %}

{% block title %}
    {{ wish.title }}
{% endblock %}